### ISSUE TITLE
List up Builtin functions

### ISSUE THREAD

**Issue by VoQn** [VoQn/cacco#10]
## Task
- [ ] prepare document
- [ ] write document about builtin functions

### Equality
- [ ] `eq? (: a Eq) (-> a a ... Bool)`/`==`
- [ ]  `unique? (: a Eq) (-> a a ... Bool)`/`!=`

### Ordering
- [ ] `greater? (: a Ord) (-> a a ... Bool)`/`>`
- [ ] `less? (: a Ord) (-> a a ... Bool)`/`<`
- [ ] `greater-or-equal? (: a Ord) (-> a a ... Bool)`/`<=`
- [ ] `less-or-equal? (: a Ord) (-> a a ... Bool)`/`>=`
- [ ] `compare (: a Ord) (-> a a Ordering)`

### Numeric operation
- [ ] `sum (: a Addible) (-> a a ... a)`/`+`
- [ ] `product (: a Multiply) (-> a a ... a)`/`*`
- [ ] `sub (-> a a ... a)`/`-`
- [ ] `div (-> a a ... a)`/`/`
- [ ] `negate (-> a a)`

### List operation
- [ ] `list`
- [ ] `head`
- [ ] `tail`
- [ ] `cons`/`unshift`/`::`
- [ ] `length`
- [ ] `nth`

### I/O
- [ ] `open-input-file`
- [ ] `close-input-file`
- [ ] `open-output-file`
- [ ] `close-output-file`
- [ ] `print`
- [ ] `read`
- [ ] `write`
